### ISSUE TITLE
Bot broken

### ISSUE THREAD

**Issue by RDIL** [RDIL/cakebot#2]
Bot is able to start and connect to discord (dot goes to green), but the RP isn’t changed and it doesn’t print anything and it doesn’t respond to messages. 

@blizowo can you please take a look

**Comment by blizowo** [comment]
what version of discord.py are you using.

**Comment by RDIL** [comment]
Oh, that may be it, I was using the final async version before, but not sure if requirements.txt is messing it up.  Will look into it

**Comment by RDIL** [comment]
Set it to `==0.16.12`.  Waiting for the servers to reboot so I can see if that fixes it.

**Comment by RDIL** [comment]
I don't have access to discord right now but logs show stuff so I think it is working!

**Comment by RDIL** [comment]
@blizowo do you happen to have access to discord right now

**Comment by RDIL** [comment]
It works! Thanks <3
